### PR TITLE
[#235] Fix email to have at least one period

### LINKED ISSUE #235: Email should have at least one period

### PR DESCRIPTION
**Pull request by xpzmichael**
fixes #235

### CODE REVIEW

File: src/test/java/seedu/address/model/person/EmailTest.java [hunk 1]
```diff
@@ -60,16 +60,16 @@ public void isValidEmail() {
         assertFalse(Email.isValidEmail("peterjack@example.com.")); // domain name ends with a period
         assertFalse(Email.isValidEmail("peterjack@-example.com")); // domain name starts with a hyphen
         assertFalse(Email.isValidEmail("peterjack@example.com-")); // domain name ends with a hyphen
-        assertFalse(Email.isValidEmail("peterjack@example.c")); // top level domain has less than two chars
```
Comment (atmh) [inline src/test/java/seedu/address/model/person/EmailTest.java:63]: Why is this test case removed? Does the changes to the regex make `isValidEmail("peterjack@example.c")` become true?

**Review by atmh — CHANGES_REQUESTED** [review]

**Comment by atmh** [comment]
Could you add a test case to check specifically for missing period and also one for multiple periods.

**Comment by atmh** [comment]
Just one more test for "peter.jack@examplecom" would be great!

**Review by atmh — APPROVED** [review]
