### PR TITLE
[#261] Fix phone

### LINKED ISSUE #261: Phone numbers country code need to be separate by space

### PR DESCRIPTION
**Pull request by xpzmichael**
fixes #261

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Phone.java [hunk 1]
```diff
@@ -11,15 +11,12 @@
...
-            "Phone numbers contains country code part and number part, country code should follow by a space. "
-                    + "country code part starts with a \"+\" and is optional. "
-                    + "Number part can only have numbers and spaces, it should contain at least 3 numbers. "
-                    + "Country code should not exceed 3 numbers. "
-                    + "The total length should not exceed "
-                    + PHONE_NUMBER_MAXIMUM + " characters"
-                    + "e.g. +65 12345678\n+123 888 777 666";
+            "Phone numbers should only contain numbers or white spaces."
+                    + " It may also contain '+' at the start, but must be followed by a number."
+                    + "  It should contain at least 3 numbers and cannot exceed "
```
Comment (atmh) [inline src/main/java/seedu/address/model/person/Phone.java:16]: There's an extra white space at the beginning

**Review by atmh — APPROVED** [review]
LGTM
