### PR TITLE
[#117] Limit number of characters for Name, Address, Email and Phone 

### LINKED ISSUE #117: Limit number of characters for Name, Address, Email and Phone
Currently, person attributes such as `Name`, `Email`, `Address`, `Phone` have no limit on the number of characters. To protect users from accidentally entering extremely long strings to these attributes, which might reduce the performance / crash the app, a reasonable limit of 1000 characters will be imposed.

### PR DESCRIPTION
**Pull request by xpzmichael**
fix #117

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Address.java [hunk 1]
```diff
@@ -9,13 +9,15 @@
...
+    private static final int MAXIMUM_LENGTH = 400;
+    public static final String MESSAGE_CONSTRAINTS = "Addresses should not be blank, "
+            + "and it has no more than" + MAXIMUM_LENGTH + "characters(excluding blank space at front)";
 
     /*
      * The first character of the address must not be a whitespace,
      * otherwise " " (a blank string) becomes a valid input.
      */
-    public static final String VALIDATION_REGEX = "[^\\s].*";
+    public static final String VALIDATION_REGEX = "[^\\s].{0," + MAXIMUM_LENGTH + "}";
```
Comment (atmh) [inline src/main/java/seedu/address/model/person/Address.java:20]: I did some light testing and the `VALIDATION_REGEX` allows `401` characters, which is more than the `MAXIMUM_LENGTH` allowed.

File: src/main/java/seedu/address/model/person/Name.java [hunk 2]
```diff
@@ -10,13 +10,15 @@
 public class Name {
 
     public static final String MESSAGE_CONSTRAINTS =
-            "Names should only contain alphanumeric characters and spaces, and it should not be blank";
+            "Names should only contain alphanumeric characters and spaces, "
+                    + "and its length should be between 1 and 30 (including spaces)";
 
+    public static final String NAME_CHARACTER_LIMIT = "{0,29}";
```
Comment (atmh) [inline src/main/java/seedu/address/model/person/Name.java:16]: 30 might be too restrictive. There are many names out there that is more than 30 characters. The longest name in the world is also close to 800 characters. To be inclusive of everyone, perhaps you could consider 800 characters as the limit?

File: src/main/java/seedu/address/model/person/Address.java [hunk 3]
```diff
@@ -9,13 +9,15 @@
  */
 public class Address {
 
-    public static final String MESSAGE_CONSTRAINTS = "Addresses can take any values, and it should not be blank";
+    private static final int MAXIMUM_LENGTH = 400;
+    public static final String MESSAGE_CONSTRAINTS = "Addresses should not be blank, "
+            + "and it has no more than" + MAXIMUM_LENGTH + "characters(excluding blank space at front)";
```
Comment (atmh) [inline src/main/java/seedu/address/model/person/Address.java:14]: For line 14, would 
```java
"and should not exceed " + MAXIMUM_LENGTH + " characters" 
```
sound better?

**Review by atmh — CHANGES_REQUESTED** [review]
A limit for phone number would be nice as well.

File: src/main/java/seedu/address/model/person/Email.java [hunk 4]
```diff
@@ -9,13 +9,15 @@
  */
 public class Email {
 
+    private static final int MAXIMUM_LENGTH = 100;
```
Comment (atmh) [inline src/main/java/seedu/address/model/person/Email.java:12]: The longest active email address seems to be 345 characters. To be inclusive, perhaps the limit could be higher? Maybe 400?

File: src/test/java/seedu/address/model/person/AddressTest.java [hunk 5]
```diff
@@ -31,6 +31,6 @@ public void isValidAddress() {
         // valid addresses
         assertTrue(Address.isValidAddress("Blk 456, Den Road, #01-355"));
         assertTrue(Address.isValidAddress("-")); // one character
-        assertTrue(Address.isValidAddress("Leng Inc; 1234 Market St; San Francisco CA 2349879; USA")); // long address
+        assertTrue(Address.isValidAddress("aaaaabbbbbcccccdddddaaaaabbbbbcccccddddd")); // long address
```
Comment (atmh) [inline src/test/java/seedu/address/model/person/AddressTest.java:34]: "Leng Inc; 1234 Market St; San Francisco CA 2349879; USA" seems like a better address to test than "aaaaabbbbbcccccdddddaaaaabbbbbcccccddddd". The former consist of a mix of alphabets, numbers, special characters and white spaces, whereas the latter is just alphabets. Is there a particular reason why this is changed as such?

File: src/main/java/seedu/address/model/person/Phone.java [hunk 6]
```diff
@@ -11,8 +11,8 @@
 
 
     public static final String MESSAGE_CONSTRAINTS =
-            "Phone numbers should only contain numbers, and it should be at least 3 digits long";
-    public static final String VALIDATION_REGEX = "\\d{3,}";
+            "Phone numbers should only contain numbers, and it should be 3 to 15 digits long";
+    public static final String VALIDATION_REGEX = "\\d{3,15}";
```
Comment (atmh) [inline src/main/java/seedu/address/model/person/Phone.java:15]: According to sources online, e.g. [link](https://stackoverflow.com/questions/723587/whats-the-longest-possible-worldwide-phone-number-i-should-consider-in-sql-varc). Maximum phone number is indeed 15. However, this is not inclusive of the prefix and suffix. If we add in prefix and suffix, the max should be 15 + 5 (prefix) + 11 (suffix) = 31.

**Review by atmh — CHANGES_REQUESTED** [review]
Just some minor nits to fix 👍 .

File: src/main/java/seedu/address/model/person/Phone.java [hunk 7]
```diff
@@ -9,10 +9,10 @@
  */
 public class Phone {
 
-
     public static final String MESSAGE_CONSTRAINTS =
-            "Phone numbers should only contain numbers, and it should be at least 3 digits long";
-    public static final String VALIDATION_REGEX = "\\d{3,}";
+            "Phone numbers should only contain numbers, and it should be 3 to 15 digits long";
```
Comment (atmh) [inline src/main/java/seedu/address/model/person/Phone.java:13]: 15 needs to be updated to 31 😃

Comment (atmh) [inline src/main/java/seedu/address/model/person/Phone.java:13]: 15 needs to be updated to 31 😃

**Review by atmh — CHANGES_REQUESTED** [review]

**Review by atmh — APPROVED** [review]
LGTM
