### PR TITLE
[#69] Fix bug found in FindCommand. 

### LINKED ISSUE #69: Fix bug found in FindCommand.
Currently, FindCommand allows the following input: ``find Alex`` but this is supposed to throw an exception as the command is in the wrong format.

### PR DESCRIPTION
**Pull request by tandeshao**
Fixes #69.

``Find alex`` would no longer work and the application would prompt the user to enter a valid command format.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/FindCommand.java [hunk 1]
```diff
@@ -17,10 +17,12 @@
...
             + ": Finds all persons whose contact details matches any of "
             + "the specified keywords (case-insensitive) and displays them as a list with index numbers.\n"
-            + "Parameters: KEYWORD /n [NAME_PARAMETER]...\n" + "n/ [NAME_PARAMETER]...\n" + "p/ [PHONE_PARAMETER]...\n"
+            + "Parameters: \n "
+            + "+ KEYWORD /n [NAME_PARAMETER]...\n" + "n/ [NAME_PARAMETER]...\n"
+            + "p/ [PHONE_PARAMETER]" + "...\n"
             + "e/ [EMAIL_PARAMETER]...\n" + "a/ [ADDRESS_PARAMETER]...\n" + "t/ [TAG_PARAMETER]...\n"
             + "m/ [MEMO_PARAMETER]...\n" + "Example: " + COMMAND_WORD + " n/ alice bob charlie" + " e/ alice@gmail.com";
-
+    public static final String MESSAGE_NOT_EDITED = "At least one field to find must be provided.";
```
Comment (atmh) [inline src/main/java/seedu/address/logic/commands/FindCommand.java:25]: Maybe `MESSAGE_NOT_FOUND` would fit better 😀

**Review by atmh — CHANGES_REQUESTED** [review]

**Review by atmh — APPROVED** [review]
LGTM
